"""build_branded_memo.py — Render a SubDirt AI branded Word memo from a JSON spec.

Generic renderer for SubDirt deliverables (Zoning & Entitlement Memorandum, feasibility memo,
site-specifics sections, ...). The skill authors a JSON spec; this script owns all branding and
formatting so no run ever re-invents styling.

Usage:
    pip install python-docx --break-system-packages
    python build_branded_memo.py spec.json out.docx

Spec schema (top level):
{
  "title":        "Zoning & Entitlement Memorandum",     # required
  "project":      "UK South Limestone Assemblage",       # required — title page + footer
  "subtitle":     "Purpose-built student housing",       # optional title-page line
  "date":         "July 17, 2026",                       # required (string, printed verbatim)
  "prepared_by":  "SubDirt AI",                          # default "SubDirt AI"
  "logo":         "path/to/subdirt_logo.png",            # optional; default: ../assets/subdirt_logo.png
  "classification": "Internal — not a legal opinion",    # footer + memo header default
  "toc":          true,                                  # insert a Word TOC field (F9 / open-update)
  "disclosure":   "...",                                 # optional override of the default disclosure
  "sections":     [ <block>, ... ]                       # the document body
}

Blocks (each an object with "type"):
  {"type":"h1"|"h2"|"h3", "text": "..."}                    headings (feed the TOC)
  {"type":"p", "text": "...", "small": false, "italic": false}
       Inline bold with **double asterisks**.
  {"type":"kv", "rows": [["To","..."],["From","..."]]}      memo header block (2-col, beige labels)
  {"type":"bluf", "text": "..."}                            beige callout box; bold **lead-ins** honored
  {"type":"table", "headers":[...], "rows":[[...]],
   "source":"...",                                          source-and-vintage line under the table
   "widths":[1.2, 2.0, ...],                                inches, optional
   "status_col": 3}                                         optional column index to color-code
  {"type":"list", "style":"number"|"bullet", "items":["..."]}
  {"type":"image", "path":"...", "width_in": 6.0, "caption":"..."}
  {"type":"pagebreak"}

Output: writes the .docx, reopens it to verify integrity, prints a JSON run summary to stdout.
"""

import json
import os
import sys

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

# ─── SubDirt brand (see assets/branding.md — change there first) ───────────────
EVEREST = "16352E"
SAGE = "4EA57E"
LIME = "C1D100"
BEIGE = "F7F1E3"
INK = "2B2B2B"
MUTED = "595959"
STATUS_GREEN = "E2EFDA"
STATUS_AMBER = "FFF2CC"
STATUS_RED_TXT = "C00000"
STATUS_RED_BG = "F8E1E1"
FONT = "Arial"

DEFAULT_LOGO = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "subdirt_logo.png")
DEFAULT_DISCLOSURE = (
    "This report was generated by SubDirt AI and is provided for informational purposes only. Data is "
    "sourced from public records and third-party providers. This report does not constitute professional "
    "or legal advice, and no representation or warranty is made regarding the accuracy, completeness, or "
    "currency of the information contained herein. Recipients should conduct independent due diligence "
    "and confirm all regulatory requirements with the governing jurisdiction and qualified land-use "
    "counsel before making decisions based on this report."
)

GREEN_TOKENS = {"PASS", "COMPLIES", "VIABLE", "GO", "LOW", "COMPLETE", "APPROVED", "YES", "Y", "P"}
AMBER_TOKENS = {"PASS*", "VIABLE*", "TBD", "VERIFY", "CONDITIONAL", "MODERATE", "PARTIAL", "PENDING", "C"}
RED_TOKENS = {"FAIL", "KILLED", "HIGH", "SEVERE", "NO", "N", "BLOCKED", "DENIED", "NOT PERMITTED"}


def shade(cell, hex_fill):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:fill"), hex_fill)
    tc_pr.append(shd)


def style_run(run, size=10, bold=False, italic=False, color=INK):
    run.font.name = FONT
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = RGBColor.from_string(color)


def add_rich_text(paragraph, text, size=10, italic=False, color=INK, base_bold=False):
    """Write text with **bold** inline segments."""
    parts = text.split("**")
    for i, part in enumerate(parts):
        if not part:
            continue
        style_run(paragraph.add_run(part), size=size, bold=base_bold or (i % 2 == 1),
                  italic=italic, color=color)


def status_fill(cell, text):
    token = text.strip().upper()
    head = token.split("—")[0].split("(")[0].strip()
    if "TO BE VERIFIED" in token or head in AMBER_TOKENS or head.startswith("TBD"):
        shade(cell, STATUS_AMBER)
    elif head in GREEN_TOKENS or head.startswith(("PASS", "COMPLIES", "VIABLE", "GO ")):
        shade(cell, STATUS_GREEN)
    elif head in RED_TOKENS or head.startswith(("FAIL", "KILLED", "NOT CLEARLY", "NOT PERMITTED", "HIGH", "SEVERE")):
        shade(cell, STATUS_RED_BG)
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.color.rgb = RGBColor.from_string(STATUS_RED_TXT)
                r.font.bold = True


def add_page_number(paragraph):
    run = paragraph.add_run()
    begin = OxmlElement("w:fldChar")
    begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"
    end = OxmlElement("w:fldChar")
    end.set(qn("w:fldCharType"), "end")
    run._r.append(begin)
    run._r.append(instr)
    run._r.append(end)
    style_run(run, size=8, color=MUTED)


class MemoBuilder:
    def __init__(self, spec):
        self.spec = spec
        self.doc = Document()
        self.counts = {"headings": 0, "tables": 0, "paragraphs": 0, "images": 0}
        self._setup_styles()
        self._setup_page()

    def _setup_styles(self):
        normal = self.doc.styles["Normal"]
        normal.font.name = FONT
        normal.font.size = Pt(10)
        normal.font.color.rgb = RGBColor.from_string(INK)
        for name, size, color, before, after in [
            ("Heading 1", 16, EVEREST, 14, 6),
            ("Heading 2", 13, EVEREST, 12, 4),
            ("Heading 3", 11, SAGE, 10, 3),
        ]:
            st = self.doc.styles[name]
            st.font.name = FONT
            st.font.size = Pt(size)
            st.font.bold = True
            st.font.color.rgb = RGBColor.from_string(color)
            st.paragraph_format.space_before = Pt(before)
            st.paragraph_format.space_after = Pt(after)

    def _setup_page(self):
        section = self.doc.sections[0]
        section.page_width, section.page_height = Inches(8.5), Inches(11)
        for side in ("left", "right", "top", "bottom"):
            setattr(section, f"{side}_margin", Inches(1))
        footer_p = section.footer.paragraphs[0]
        footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        style_run(
            footer_p.add_run(
                f"{self.spec['project']}  ·  "
                f"{self.spec.get('classification', 'Internal — not a legal opinion')}  ·  p. "
            ),
            size=8, color=MUTED,
        )
        add_page_number(footer_p)

    # ── title page & TOC ──────────────────────────────────────────────────────
    def title_page(self):
        for _ in range(4):
            self.doc.add_paragraph()
        logo = self.spec.get("logo") or DEFAULT_LOGO
        if os.path.isfile(logo):
            p = self.doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            p.add_run().add_picture(logo, width=Inches(2.8))
            self.counts["images"] += 1
        self.doc.add_paragraph()
        for text, size, bold, color in [
            (self.spec["title"], 24, True, EVEREST),
            (self.spec["project"], 14, False, INK),
            (self.spec.get("subtitle", ""), 12, False, MUTED),
            ("Opportunity Intelligence for Land Development", 10, False, SAGE),
            (f"Prepared by {self.spec.get('prepared_by', 'SubDirt AI')} · {self.spec['date']}", 10, False, MUTED),
        ]:
            if not text:
                continue
            p = self.doc.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            style_run(p.add_run(text), size=size, bold=bold, color=color)
        self.doc.add_page_break()

    def toc(self):
        p = self.doc.add_paragraph()
        style_run(p.add_run("Contents"), size=13, bold=True, color=EVEREST)
        fld = OxmlElement("w:fldSimple")
        fld.set(qn("w:instr"), 'TOC \\o "1-3" \\h \\z \\u')
        inner = OxmlElement("w:r")
        t = OxmlElement("w:t")
        t.text = "Right-click → Update Field (or Ctrl+A, F9) to populate the table of contents."
        inner.append(t)
        fld.append(inner)
        self.doc.add_paragraph()._p.append(fld)
        self.doc.add_page_break()

    # ── blocks ────────────────────────────────────────────────────────────────
    def block(self, b):
        t = b["type"]
        if t in ("h1", "h2", "h3"):
            self.doc.add_heading(b["text"], level=int(t[1]))
            self.counts["headings"] += 1
        elif t == "p":
            p = self.doc.add_paragraph()
            add_rich_text(p, b["text"], size=8 if b.get("small") else 10,
                          italic=b.get("italic", False),
                          color=MUTED if b.get("small") else INK)
            self.counts["paragraphs"] += 1
        elif t == "kv":
            table = self.doc.add_table(rows=0, cols=2)
            table.style = "Table Grid"
            for label, value in b["rows"]:
                cells = table.add_row().cells
                cells[0].width, cells[1].width = Inches(1.1), Inches(5.4)
                style_run(cells[0].paragraphs[0].add_run(label), size=9, bold=True, color=EVEREST)
                shade(cells[0], BEIGE)
                add_rich_text(cells[1].paragraphs[0], str(value), size=9)
            self.counts["tables"] += 1
        elif t == "bluf":
            table = self.doc.add_table(rows=1, cols=1)
            table.style = "Table Grid"
            cell = table.rows[0].cells[0]
            shade(cell, BEIGE)
            add_rich_text(cell.paragraphs[0], b["text"], size=10)
            self.counts["tables"] += 1
        elif t == "table":
            headers, rows = b["headers"], b["rows"]
            table = self.doc.add_table(rows=1, cols=len(headers))
            table.style = "Table Grid"
            table.autofit = b.get("widths") is None
            for i, h in enumerate(headers):
                cell = table.rows[0].cells[i]
                style_run(cell.paragraphs[0].add_run(str(h)), size=9, bold=True, color="FFFFFF")
                shade(cell, EVEREST)
            for row in rows:
                cells = table.add_row().cells
                for i, value in enumerate(row):
                    add_rich_text(cells[i].paragraphs[0], str(value), size=9)
                    if b.get("status_col") == i:
                        status_fill(cells[i], str(value))
            if b.get("widths"):
                for row in table.rows:
                    for i, w in enumerate(b["widths"]):
                        if i < len(row.cells):
                            row.cells[i].width = Inches(w)
            if b.get("source"):
                p = self.doc.add_paragraph()
                add_rich_text(p, "Source & vintage: " + b["source"], size=8, italic=True, color=MUTED)
            self.counts["tables"] += 1
        elif t == "list":
            style = "List Number" if b.get("style") == "number" else "List Bullet"
            for item in b["items"]:
                p = self.doc.add_paragraph(style=style)
                add_rich_text(p, item, size=10)
                self.counts["paragraphs"] += 1
        elif t == "image":
            if os.path.isfile(b["path"]):
                p = self.doc.add_paragraph()
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER
                p.add_run().add_picture(b["path"], width=Inches(b.get("width_in", 6.0)))
                self.counts["images"] += 1
                if b.get("caption"):
                    cap = self.doc.add_paragraph()
                    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER
                    add_rich_text(cap, b["caption"], size=8, italic=True, color=MUTED)
            else:
                p = self.doc.add_paragraph()
                add_rich_text(p, f"[Image not found: {b['path']}]", size=8, italic=True, color=STATUS_RED_TXT)
        elif t == "pagebreak":
            self.doc.add_page_break()
        else:
            raise ValueError(f"Unknown block type: {t}")

    def disclosure(self):
        self.doc.add_page_break()
        p = self.doc.add_paragraph()
        style_run(p.add_run("Disclosure"), size=13, bold=True, color=EVEREST)
        p = self.doc.add_paragraph()
        add_rich_text(p, self.spec.get("disclosure", DEFAULT_DISCLOSURE), size=9, color=MUTED)

    def build(self, out_path):
        self.title_page()
        if self.spec.get("toc", True):
            self.toc()
        for b in self.spec["sections"]:
            self.block(b)
        self.disclosure()
        self.doc.save(out_path)
        return self.counts


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: python build_branded_memo.py spec.json out.docx")
    spec_path, out_path = sys.argv[1], sys.argv[2]
    with open(spec_path, encoding="utf-8") as f:
        spec = json.load(f)
    for key in ("title", "project", "date", "sections"):
        if key not in spec:
            sys.exit(f"spec missing required key: {key}")
    counts = MemoBuilder(spec).build(out_path)
    # verification pass: reopen and confirm integrity
    check = Document(out_path)
    summary = {
        "status": "ok",
        "output": os.path.abspath(out_path),
        "built": counts,
        "verified": {"paragraphs": len(check.paragraphs), "tables": len(check.tables)},
        "note": "Open in Word and update fields (Ctrl+A, F9) to populate the table of contents.",
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
